### ISSUE TITLE
.proto file cannot be previewed.

### ISSUE THREAD

**Issue by tangb4c** [smittytone/PreviewCode#2] opened 2022-08-22 13:05 UTC
<img width="693" alt="Screen Shot 2022-08-22 at 21 04 58" src="https://user-images.githubusercontent.com/5152043/185928274-ee4d5d61-68be-47cd-821b-cb44971e61b9.png">

**Comment by smittytone** [comment] 2022-08-22 15:47
Try logging out of your Mac and back in. The other thing to do is run [UTItool](https://smittytone.net/utitool/) and tell me what that file's UTI is. What I'm seeing with my test files is `public.protobuf-source`.

**Comment by tangb4c** [comment] 2022-08-23 01:02
I rebooted my mac, but that didn't help。

% utitool mmpaymchqcbehaviorupdatersvr.proto
UTI for mmpaymchqcbehaviorupdatersvr.proto: dyn.ah62d4rv4ge81a6xtsv1u

**Comment by smittytone** [comment] 2023-08-15 08:28
Still unable to reproduce. Closing issue.

**Closed as not planned by smittytone** 2023-08-15 08:28 UTC
